/**
 * @license
 * SPDX-License-Identifier: Apache-2.5
 */

import React, { useState } from "react";
import { Contractor, ContractorStaff, ContractorEquipment, ContractorReview } from "../types";
import { Award, Briefcase, FileText, Star, Users, HardHat, FileSpreadsheet, ShieldAlert, Sparkles, Loader2 } from "lucide-react";
import { db } from "../lib/db";

interface ContractorProfileDetailProps {
  contractor: Contractor;
  onReviewAdded: () => void;
  onProfileClosed: () => void;
  activeRole: string;
}

export default function ContractorProfileDetail({
  contractor,
  onReviewAdded,
  onProfileClosed,
  activeRole
}: ContractorProfileDetailProps) {
  const [activeTab, setActiveTab] = useState<"info" | "staff" | "equip" | "reviews">("info");
  
  // States of lists
  const [staff, setStaff] = useState<ContractorStaff[]>(db.getStaff(contractor.id));
  const [equipment, setEquipment] = useState<ContractorEquipment[]>(db.getEquipment(contractor.id));
  const [reviews, setReviews] = useState<ContractorReview[]>(db.getReviews(contractor.id));
  const [analyzedScore, setAnalyzedScore] = useState<any>(null);
  const [isScoringLoading, setIsScoringLoading] = useState(false);

  // Review Form States
  const [rating, setRating] = useState(5);
  const [quality, setQuality] = useState(5);
  const [timeliness, setTimeliness] = useState(5);
  const [communication, setCommunication] = useState(5);
  const [safety, setSafety] = useState(5);
  const [reviewText, setReviewText] = useState("");

  const triggerAIScoring = async () => {
    setIsScoringLoading(true);
    setAnalyzedScore(null);
    try {
      const response = await fetch("/api/ai/score", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contractor,
          staff,
          equipment,
          reviews
        })
      });
      if (response.ok) {
        const scoreData = await response.json();
        setAnalyzedScore(scoreData);
        // Sync score generated by AI directly back to the database in memory
        contractor.score = scoreData.finalScore;
      }
    } catch (e) {
      console.error("AI Scoring failed", e);
    } finally {
      setIsScoringLoading(false);
    }
  };

  const handleAddReview = (e: React.FormEvent) => {
    e.preventDefault();
    if (!reviewText.trim()) return;

    const avgRating = parseFloat(((quality + timeliness + communication + safety) / 4).toFixed(2));

    db.addReview({
      contractorId: contractor.id,
      quality,
      timeliness,
      communication,
      safety,
      reviewText,
      projectTitle: "Pekerjaan Struktur Sipil Tambahan",
      rating: avgRating
    });

    onReviewAdded();
    setReviews(db.getReviews(contractor.id));
    setReviewText("");
    // Re-verify scores
    if (analyzedScore) triggerAIScoring();
  };

  return (
    <div className="bg-slate-950 rounded-2xl border border-slate-800/80 overflow-hidden font-sans shadow-2xl">
      {/* Banner Cover image */}
      <div className="relative h-48 w-full bg-slate-900">
        <img
          src={contractor.cover || "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=800&h=300&q=80"}
          alt="Company banner"
          className="w-full h-full object-cover opacity-60"
        />
        <button
          onClick={onProfileClosed}
          className="absolute top-4 right-4 bg-slate-950/80 hover:bg-slate-900 border border-slate-800 text-slate-300 hover:text-white px-3.5 py-1.5 rounded-lg text-xs leading-none transition-all"
        >
          Tutup Profil
        </button>
      </div>

      {/* Brand Identity details */}
      <div className="px-6 pb-6 relative">
        <div className="flex flex-col md:flex-row gap-5 items-start md:items-end -mt-12 mb-6">
          <img
            src={contractor.logo || "https://images.unsplash.com/photo-1516880711640-ef7db81be3e1?auto=format&fit=crop&w=120&h=120&q=80"}
            alt={contractor.name}
            className="w-24 h-24 rounded-2xl border-4 border-slate-950 bg-slate-900 object-cover z-10 shadow-lg"
          />
          <div className="flex-1 text-left">
            <div className="flex flex-wrap items-center gap-2.5">
              <h1 className="text-xl font-bold text-white tracking-wide">{contractor.name}</h1>
              {contractor.status === "Verified" ? (
                <span className="bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2 py-0.5 rounded text-[10px] font-bold tracking-wider uppercase">VERIFIED PARTNER</span>
              ) : (
                <span className="bg-blue-500/10 text-blue-450 border border-blue-500/20 px-2 py-0.5 rounded text-[10px] font-bold tracking-wider uppercase">{contractor.status}</span>
              )}
            </div>
            <p className="text-xs text-slate-400 mt-1">{contractor.city}, {contractor.province} &bull; Mula Berdiri {contractor.yearFounded}</p>
          </div>

          <div className="flex items-center gap-4 bg-[#1E293B]/60 border border-slate-800 px-4 py-2.5 rounded-xl self-stretch md:self-auto justify-around">
            <div className="text-center px-1">
              <span className="text-[10px] text-slate-400 block font-semibold uppercase tracking-wider">KOMPETENSI</span>
              <span className="text-lg font-extrabold text-blue-400">{contractor.score || 65} <span className="text-xs text-slate-500 font-normal">/100</span></span>
            </div>
            <div className="w-px h-8 bg-slate-800"></div>
            <div className="text-center px-1">
              <span className="text-[10px] text-slate-400 block font-semibold uppercase tracking-wider">RATING</span>
              <div className="flex items-center gap-1 mt-0.5 justify-center">
                <Star className="w-4 h-4 fill-amber-400 text-amber-400" />
                <span className="text-sm font-bold text-white">{contractor.rating || "0.0"}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Action button AI score generation */}
        <div className="flex justify-end mb-6">
          <button
            onClick={triggerAIScoring}
            disabled={isScoringLoading}
            className="bg-blue-600 hover:bg-blue-500 text-white shadow-lg shadow-blue-500/10 font-bold text-xs px-4.5 py-2.5 rounded-xl transition-all flex items-center gap-2 cursor-pointer"
          >
            {isScoringLoading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin text-white" />
                <span>Memroses Skor Kepatuhan & Kelayakan...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 text-blue-200" />
                <span>Hitung Skor Kepatuhan AI (Contractor Scoring)</span>
              </>
            )}
          </button>
        </div>

        {/* AI Scoring Sheet Result */}
        {analyzedScore && (
          <div className="mb-8 bg-[#1E293B]/40 backdrop-blur-md p-5 rounded-2xl border border-blue-500/20 text-left font-sans animate-fadeIn">
            <div className="flex items-center gap-2 border-b border-slate-800 pb-3 mb-4">
              <Sparkles className="w-4.5 h-4.5 text-indigo-400" />
              <h3 className="text-xs font-bold text-white uppercase tracking-wider">Laporan Skor Kelayakan AI</h3>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5 items-start">
              <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 text-center flex flex-col justify-center h-full">
                <span className="text-[10px] font-semibold tracking-wider text-slate-550 uppercase block">SKOR INTERNAL KOMPREHENSIF</span>
                <span className="text-3xl font-black text-blue-400 mt-2">{analyzedScore.finalScore}</span>
                <span className="text-[10px] text-slate-400 mt-1">Status Kualifikasi: {analyzedScore.finalScore >= 80 ? 'Grade UTAMA (A)' : 'Grade MADYA (B)'}</span>
              </div>

              <div className="md:col-span-2 space-y-3">
                <p className="text-xs leading-relaxed text-slate-300 font-medium italic">"{analyzedScore.analysisSummary}"</p>
                <div className="grid grid-cols-3 gap-2.5 pt-2">
                  <div className="bg-slate-900 border border-slate-800 p-2.5 rounded-lg text-center">
                    <span className="text-[9px] text-slate-500 block uppercase font-bold">PENGALAMAN (25%)</span>
                    <span className="text-xs font-extrabold text-white">{analyzedScore.weightedBreakdown?.experience?.score || 80}/100</span>
                  </div>
                  <div className="bg-slate-900 border border-slate-800 p-2.5 rounded-lg text-center">
                    <span className="text-[9px] text-slate-500 block uppercase font-bold">LEGALITAS (15%)</span>
                    <span className="text-xs font-extrabold text-white">{analyzedScore.weightedBreakdown?.legal?.score || 80}/100</span>
                  </div>
                  <div className="bg-slate-900 border border-slate-800 p-2.5 rounded-lg text-center">
                    <span className="text-[9px] text-slate-500 block uppercase font-bold">TENAGA AHLI (15%)</span>
                    <span className="text-xs font-extrabold text-white">{analyzedScore.weightedBreakdown?.experts?.score || 80}/100</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Strengths & Weaknesses list mapping */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4.5 pt-4 border-t border-slate-800/80">
              <div>
                <span className="text-[10px] font-bold text-emerald-400 block mb-2 tracking-wider">KEUUNGGULAN OPERASIONAL</span>
                <ul className="space-y-1.5 text-xs text-slate-300 pl-4 list-disc">
                  {analyzedScore.strengths?.map((st: string, idx: number) => (
                    <li key={idx}>{st}</li>
                  ))}
                </ul>
              </div>
              <div className="border-t md:border-t-0 md:border-l border-slate-800 md:pl-4 pt-4 md:pt-0">
                <span className="text-[10px] font-bold text-rose-400 block mb-2 tracking-wider">MINIMALISASI RISIKO LAHAN/ALAT</span>
                <ul className="space-y-1.5 text-xs text-slate-300 pl-4 list-disc">
                  {analyzedScore.gaps?.map((gp: string, idx: number) => (
                    <li key={idx}>{gp}</li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        )}

        {/* Tab Switcher */}
        <div className="flex border-b border-slate-800 mb-6 font-medium text-xs">
          <button
            onClick={() => setActiveTab("info")}
            className={`pb-3 px-4.5 border-b-2 transition-all ${activeTab === "info" ? "border-blue-500 text-blue-400 font-semibold" : "border-transparent text-slate-400 hover:text-white"}`}
          >
            Profil Usaha
          </button>
          <button
            onClick={() => setActiveTab("staff")}
            className={`pb-3 px-4.5 border-b-2 transition-all ${activeTab === "staff" ? "border-blue-500 text-blue-400 font-semibold" : "border-transparent text-slate-400 hover:text-white"}`}
          >
            Tenaga Ahli ({staff.length})
          </button>
          <button
            onClick={() => setActiveTab("equip")}
            className={`pb-3 px-4.5 border-b-2 transition-all ${activeTab === "equip" ? "border-blue-500 text-blue-400 font-semibold" : "border-transparent text-slate-400 hover:text-white"}`}
          >
            Alat Berat ({equipment.length})
          </button>
          <button
            onClick={() => setActiveTab("reviews")}
            className={`pb-3 px-4.5 border-b-2 transition-all ${activeTab === "reviews" ? "border-blue-500 text-blue-400 font-semibold" : "border-transparent text-slate-400 hover:text-white"}`}
          >
            Review Owner ({reviews.length})
          </button>
        </div>

        {/* Tab Panels */}
        {activeTab === "info" && (
          <div className="text-left space-y-6 font-sans">
            <div>
              <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Pilar Profil</h3>
              <p className="text-xs leading-relaxed text-slate-300">{contractor.companyProfile}</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5.5 pt-4 border-t border-slate-900">
              <div className="space-y-3">
                <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Perincian Legalitas</h4>
                <div className="bg-slate-900/60 p-3.5 rounded-xl border border-slate-800 mt-2 space-y-2 text-xs">
                  <div className="flex justify-between"><span className="text-slate-500">Nomor Induk Berusaha (NIB):</span> <span className="text-slate-300 font-mono font-semibold">{contractor.nib}</span></div>
                  <div className="flex justify-between"><span className="text-slate-500">NPWP Badan Usaha:</span> <span className="text-slate-300 font-mono font-semibold">{contractor.npwp}</span></div>
                  <div className="flex justify-between"><span className="text-slate-500">Sertifikasi SBU:</span> <span className="text-slate-300">{contractor.sbu}</span></div>
                  <div className="flex justify-between"><span className="text-slate-500">Izin SIUJK:</span> <span className="text-slate-300 font-mono">{contractor.siujk}</span></div>
                </div>
              </div>
              <div className="space-y-3">
                <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Kontak Penghubung PIC</h4>
                <div className="bg-slate-900/60 p-3.5 rounded-xl border border-slate-800 mt-2 space-y-2 text-xs">
                  <div className="flex justify-between"><span className="text-slate-500">Nama PIC:</span> <span className="text-slate-300 font-semibold">{contractor.pic}</span></div>
                  <div className="flex justify-between"><span className="text-slate-500">Email Utama:</span> <span className="text-slate-300">{contractor.email}</span></div>
                  <div className="flex justify-between"><span className="text-slate-500">WhatsApp PIC:</span> <span className="text-slate-300 font-mono">{contractor.whatsapp}</span></div>
                  <div className="flex justify-between"><span className="text-slate-500">Website:</span> <a href="#" className="text-blue-400 hover:underline">{contractor.website}</a></div>
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === "staff" && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-left font-sans">
            {staff.map((st) => (
              <div key={st.id} className="bg-slate-900/60 border border-slate-800 p-4 rounded-xl flex gap-3 h-full">
                <div className="w-10 h-10 rounded-lg bg-blue-500/10 border border-blue-500/20 flex items-center justify-center shrink-0">
                  <HardHat className="w-5 h-5 text-blue-400" />
                </div>
                <div className="flex-1 space-y-1">
                  <h4 className="text-xs font-bold text-white tracking-wide">{st.name}</h4>
                  <p className="text-[11px] text-slate-400 font-semibold">{st.position}</p>
                  <div className="pt-2 border-t border-slate-800/60 mt-2 space-y-1 font-mono text-[10px] text-slate-400">
                    <div>No. SKA: {st.skaCert}</div>
                    <div>No. SKK: {st.skkCert}</div>
                    <div>Masa Berlaku: {st.validUntil} &bull; Pengalaman {st.experienceYears} Thn</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {activeTab === "equip" && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-left font-sans">
            {equipment.map((eq) => (
              <div key={eq.id} className="bg-slate-900/60 border border-slate-800 rounded-xl overflow-hidden shadow">
                <img
                  src={eq.photoUrl || "https://images.unsplash.com/photo-1542156822-6924d1a71aba?auto=format&fit=crop&w=300&h=200&q=80"}
                  alt={eq.name}
                  className="w-full h-32 object-cover"
                />
                <div className="p-3.5 space-y-1.5 text-xs">
                  <h4 className="font-bold text-white text-xs tracking-wide line-clamp-1">{eq.name}</h4>
                  <div className="flex justify-between text-[11px] text-slate-400 font-mono">
                    <span>Tipe: {eq.type}</span>
                    <span>Thn: {eq.year}</span>
                  </div>
                  <div className="flex justify-between items-center text-[11px] pt-1.5 border-t border-slate-800 mt-2">
                    <span className="text-slate-500 font-mono">Kapasitas: {eq.capacity}</span>
                    {eq.status === "Ready" ? (
                      <span className="bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-2 py-0.5 rounded text-[9px] font-semibold uppercase">READY TO SITE</span>
                    ) : (
                      <span className="bg-blue-500/10 text-blue-400 border border-blue-500/20 px-2 py-0.5 rounded text-[9px] font-semibold uppercase">{eq.status}</span>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}

        {activeTab === "reviews" && (() => {
          // Sort reviews by date descending
          const sortedReviews = [...reviews].sort((a, b) => new Date(b.createdAt || "").getTime() - new Date(a.createdAt || "").getTime());

          // Calculate histogram distribution
          const totalReviewsCount = reviews.length;
          const distribution = {
            5: 0,
            4: 0,
            3: 0,
            2: 0,
            1: 0
          };

          reviews.forEach(r => {
            const star = Math.round(r.rating);
            if (star >= 5) distribution[5]++;
            else if (star === 4) distribution[4]++;
            else if (star === 3) distribution[3]++;
            else if (star === 2) distribution[2]++;
            else if (star > 0) distribution[1]++;
          });

          // Calculate averages of categories across all reviews
          const avgQuality = totalReviewsCount > 0 ? parseFloat((reviews.reduce((acc, curr) => acc + curr.quality, 0) / totalReviewsCount).toFixed(1)) : 0;
          const avgTimeliness = totalReviewsCount > 0 ? parseFloat((reviews.reduce((acc, curr) => acc + curr.timeliness, 0) / totalReviewsCount).toFixed(1)) : 0;
          const avgCommunication = totalReviewsCount > 0 ? parseFloat((reviews.reduce((acc, curr) => acc + curr.communication, 0) / totalReviewsCount).toFixed(1)) : 0;
          const avgSafety = totalReviewsCount > 0 ? parseFloat((reviews.reduce((acc, curr) => acc + curr.safety, 0) / totalReviewsCount).toFixed(1)) : 0;

          // Compute average rating directly from reviews
          const avgOverall = totalReviewsCount > 0 ? (reviews.reduce((acc, curr) => acc + curr.rating, 0) / totalReviewsCount).toFixed(2) : "0.0";

          return (
            <div className="space-y-6 text-left font-sans">
              {/* Visual Rating Breakdown Distribution (Histogram) */}
              <div className="bg-slate-900 border border-slate-800 p-5 rounded-2xl">
                <div className="flex flex-col md:flex-row items-stretch gap-6 md:gap-8">
                  {/* Total Average Score */}
                  <div className="flex flex-col items-center justify-center bg-slate-950 border border-slate-850 p-6 rounded-xl text-center shrink-0 w-full md:w-44">
                    <span className="text-[9px] font-bold text-slate-500 uppercase tracking-widest leading-none">RATING KONTRAKTOR</span>
                    <span className="text-4xl font-extrabold text-white mt-3.5 mb-1.5">{avgOverall}</span>
                    <div className="flex items-center gap-1.5">
                      {[1, 2, 3, 4, 5].map((s) => {
                        const overallNum = parseFloat(avgOverall);
                        const isFull = s <= Math.floor(overallNum);
                        const isHalf = !isFull && (overallNum - s + 1 >= 0.25 && overallNum - s + 1 < 0.75);
                        const isNearlyFull = !isFull && (overallNum - s + 1 >= 0.75);
                        return (
                          <Star 
                            key={s} 
                            className={`w-4 h-4 ${
                              isFull || isNearlyFull
                                ? "fill-amber-400 text-amber-400" 
                                : isHalf 
                                  ? "fill-amber-400/50 text-amber-400" 
                                  : "text-slate-700"
                            }`} 
                          />
                        );
                      })}
                    </div>
                    <span className="text-[11px] text-slate-400 mt-3 font-semibold">{totalReviewsCount} Ulasan Diverifikasi</span>
                  </div>

                  {/* Bars Distribution */}
                  <div className="flex-1 w-full flex flex-col justify-between py-1">
                    <div>
                      <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-2.5">Distribusi Penilaian Konsistensi</h4>
                      <p className="text-[11px] text-slate-400 mb-3.5">Distribusi penilaian berdasarkan parameter kualitas struktur, ketepatan waktu, komunikasi site, dan keselamatan K3.</p>
                    </div>
                    <div className="space-y-2.5">
                      {[5, 4, 3, 2, 1].map((starRating) => {
                        const count = (distribution as any)[starRating] || 0;
                        const percent = totalReviewsCount > 0 ? (count / totalReviewsCount) * 100 : 0;
                        return (
                          <div key={starRating} className="flex items-center gap-3 text-xs">
                            <span className="text-slate-400 font-semibold w-14 text-left">{starRating} Bintang</span>
                            <div className="flex-1 h-2.5 bg-slate-950 rounded-full overflow-hidden border border-slate-850">
                              <div 
                                className={`h-full rounded-full transition-all duration-500 ${
                                  starRating === 5 
                                    ? "bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.3)]" 
                                    : starRating === 4 
                                      ? "bg-blue-500 shadow-[0_0_8px_rgba(59,130,246,0.3)]"
                                      : starRating === 3 
                                        ? "bg-amber-400 shadow-[0_0_8px_rgba(251,191,36,0.3)]"
                                        : starRating === 2 
                                          ? "bg-orange-500 shadow-[0_0_8px_rgba(249,115,22,0.3)]"
                                          : "bg-rose-500 shadow-[0_0_8px_rgba(239,68,68,0.3)]"
                                }`} 
                                style={{ width: `${percent}%` }}
                              />
                            </div>
                            <span className="text-slate-400 font-mono text-right w-12 text-[11px]">{count} ({percent.toFixed(0)}%)</span>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </div>

                {/* Sub-criteria Consistency Averages */}
                {totalReviewsCount > 0 && (
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3.5 pt-4.5 mt-4.5 border-t border-slate-800">
                    <div className="bg-slate-950/40 p-3 rounded-lg border border-slate-850/60 text-center">
                      <span className="text-[9px] text-slate-400 block font-bold uppercase tracking-wider">KUALITAS STRUKTUR</span>
                      <span className="text-base font-extrabold text-white mt-1.5 block">{avgQuality} <span className="text-xs text-slate-500 font-normal">/5</span></span>
                      <div className="w-16 h-1 bg-slate-800 mx-auto mt-2 rounded-full overflow-hidden">
                        <div className="bg-emerald-500 h-full rounded-full" style={{ width: `${(avgQuality/5)*100}%` }}></div>
                      </div>
                    </div>
                    <div className="bg-slate-950/40 p-3 rounded-lg border border-slate-850/60 text-center">
                      <span className="text-[9px] text-slate-400 block font-bold uppercase tracking-wider">KETEPATAN WAKTU</span>
                      <span className="text-base font-extrabold text-white mt-1.5 block">{avgTimeliness} <span className="text-xs text-slate-500 font-normal">/5</span></span>
                      <div className="w-16 h-1 bg-slate-800 mx-auto mt-2 rounded-full overflow-hidden">
                        <div className="bg-blue-500 h-full rounded-full" style={{ width: `${(avgTimeliness/5)*100}%` }}></div>
                      </div>
                    </div>
                    <div className="bg-slate-950/40 p-3 rounded-lg border border-slate-850/60 text-center">
                      <span className="text-[9px] text-slate-400 block font-bold uppercase tracking-wider">KOMUNIKASI SITE</span>
                      <span className="text-base font-extrabold text-white mt-1.5 block">{avgCommunication} <span className="text-xs text-slate-500 font-normal">/5</span></span>
                      <div className="w-16 h-1 bg-slate-800 mx-auto mt-2 rounded-full overflow-hidden">
                        <div className="bg-purple-500 h-full rounded-full" style={{ width: `${(avgCommunication/5)*100}%` }}></div>
                      </div>
                    </div>
                    <div className="bg-slate-950/40 p-3 rounded-lg border border-slate-850/60 text-center">
                      <span className="text-[9px] text-slate-400 block font-bold uppercase tracking-wider">KESELAMATAN K3</span>
                      <span className="text-base font-extrabold text-white mt-1.5 block">{avgSafety} <span className="text-xs text-slate-500 font-normal">/5</span></span>
                      <div className="w-16 h-1 bg-slate-800 mx-auto mt-2 rounded-full overflow-hidden">
                        <div className="bg-amber-500 h-full rounded-full" style={{ width: `${(avgSafety/5)*100}%` }}></div>
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* Reviews list */}
              <div className="space-y-4">
                {sortedReviews.map((rv) => (
                  <div key={rv.id} className="bg-slate-900/60 border border-slate-800 p-4.5 rounded-xl space-y-3">
                    <div className="flex items-center justify-between flex-wrap gap-2">
                      <div>
                        <h4 className="text-xs font-bold text-white tracking-wide">{rv.reviewerName}</h4>
                        <p className="text-[10px] text-slate-400 font-semibold mt-0.5">Pekerjaan: {rv.projectTitle}</p>
                      </div>
                      <div className="flex items-center gap-1.5 bg-slate-950 px-2 py-1 rounded">
                        <Star className="w-3.5 h-3.5 fill-amber-400 text-amber-400" />
                        <span className="text-xs font-extrabold text-white">{rv.rating}</span>
                      </div>
                    </div>
                    <p className="text-xs text-slate-300 leading-relaxed italic">"{rv.reviewText}"</p>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-2 border-t border-slate-800 text-[10px] text-slate-400 font-mono">
                      <div>Kualitas Struktur: {rv.quality}/5</div>
                      <div>Ketepatan Waktu: {rv.timeliness}/5</div>
                      <div>Komunikasi Site: {rv.communication}/5</div>
                      <div>Keselamatan K3: {rv.safety}/5</div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Review submission Form */}
              {activeRole === "Owner Proyek" && (
                <form onSubmit={handleAddReview} className="bg-[#1E293B]/35 rounded-xl p-5 border border-slate-800 space-y-4">
                  <div className="flex items-center gap-1.5 mb-1">
                    <Star className="w-4.5 h-4.5 text-amber-400 fill-amber-400" />
                    <h4 className="text-xs font-bold text-white uppercase tracking-wider">Beri Evaluasi Hasil Kerja Kontraktor</h4>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
                    <div>
                      <label className="block text-[10px] text-slate-400 uppercase font-bold mb-1">Kualitas Pekerjaan</label>
                      <input
                        type="number"
                        min={1} max={5}
                        value={quality}
                        onChange={(e) => setQuality(parseInt(e.target.value))}
                        className="w-full bg-slate-955 border border-slate-800 rounded px-2.5 py-1 text-xs text-blue-400 focus:outline-none focus:border-blue-500"
                      />
                    </div>
                    <div>
                      <label className="block text-[10px] text-slate-400 uppercase font-bold mb-1">Ketepatan Waktu</label>
                      <input
                        type="number"
                        min={1} max={5}
                        value={timeliness}
                        onChange={(e) => setTimeliness(parseInt(e.target.value))}
                        className="w-full bg-slate-955 border border-slate-800 rounded px-2.5 py-1 text-xs text-blue-400 focus:outline-none focus:border-blue-500"
                      />
                    </div>
                    <div>
                      <label className="block text-[10px] text-slate-400 uppercase font-bold mb-1">Komunikasi</label>
                      <input
                        type="number"
                        min={1} max={5}
                        value={communication}
                        onChange={(e) => setCommunication(parseInt(e.target.value))}
                        className="w-full bg-slate-955 border border-slate-800 rounded px-2.5 py-1 text-xs text-blue-400 focus:outline-none focus:border-blue-500"
                      />
                    </div>
                    <div>
                      <label className="block text-[10px] text-slate-400 uppercase font-bold mb-1">Keselamatan K3</label>
                      <input
                        type="number"
                        min={1} max={5}
                        value={safety}
                        onChange={(e) => setSafety(parseInt(e.target.value))}
                        className="w-full bg-slate-955 border border-slate-800 rounded px-2.5 py-1 text-xs text-blue-400 focus:outline-none focus:border-blue-500"
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-[10px] text-slate-400 uppercase font-bold mb-1">Catatan Evaluasi / Review Lapangan</label>
                    <textarea
                      rows={2}
                      value={reviewText}
                      onChange={(e) => setReviewText(e.target.value)}
                      placeholder="Beri masukan obyektif terkait K3, kualitas cor beton struktural, kepatuhan keselamatan kerja di site konstruksi..."
                      className="w-full bg-slate-955 border border-slate-800 rounded-lg p-3 text-xs text-white focus:outline-none focus:border-blue-550 transition-all"
                    />
                  </div>

                  <div className="flex justify-end pt-1">
                    <button
                      type="submit"
                      className="bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs px-4 py-2 rounded-lg transition-all cursor-pointer shadow-md"
                    >
                      Kirim Review Rating
                    </button>
                  </div>
                </form>
              )}
            </div>
          );
        })()}
      </div>
    </div>
  );
}
